// 
//  OAuthTester.cs
//  
//  Author:
//       Robert Nordan <rpvn@robpvn.net>
// 
//  Copyright (c) 2012 Robert Nordan
// 
//  This library is free software; you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as
//  published by the Free Software Foundation; either version 2.1 of the
//  License, or (at your option) any later version.
// 
//  This library is distributed in the hope that it will be useful, but
//  WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
//  Lesser General Public License for more details.
// 
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
using System;
using Tomboy;
using Tomboy.Sync.Snowy;
namespace OAuthSetUpTester
{
	public class OAuthTester
	{
		public OAuthTester ()
		{
		}

		public static void  Main (string[] args)
		{
			Console.WriteLine ("Manual OAuth tester for Tomboy-lib (Can't be automated due to user interaction and a valid acocunt being needed.)");
			Console.WriteLine ("Starting setup process...");

			Engine engine = new Engine (new DummyStorage ());

			WebSyncAgent agent = new WebSyncAgent (engine);
			engine.SyncAgent = agent;

			string authUrl = agent.StartSettingUpNewWebSyncConnection ("https://edge.tomboy-online.org/", "http://projects.gnome.org/tomboy/");

			Console.WriteLine ("Please visit the link provided, find the OAuth_verifier info from the callback URL, then come back and enter it:");
			Console.WriteLine (authUrl);
			string verifier = Console.ReadLine ();

			bool finished = agent.FinishSettingUpWebSyncConnection (verifier);

			if (!finished)
				Console.WriteLine ("Failure! Something went wrong.");
				
			else {
				Console.WriteLine ("Success! Username is " + agent.UserName);
				Console.WriteLine ("Choose next action: 1 for download all and overwrite, 2 for upload all and overwrite");
				int action = int.Parse (Console.ReadLine ());
				

				if (action == 1) {
					Console.WriteLine ("Next up: downloading all remote notes");
					agent.CopyFromRemote ();
					
					foreach (var note in engine.GetNotes ().Values) {
						Console.WriteLine(note.Title);
					}
					Console.WriteLine ("If you saw lots of titles you should be good!");
					

				} else if (action == 2) {
					Console.WriteLine ("Next up: uploading some example notes");

					Note note1 = engine.NewNote ();
					note1.Title = "Upload test note " + System.DateTime.Now;
					note1.Text = "Simple test note generated by tester";
					engine.SaveNote (note1);


					agent.CopyFromLocal ();

					Console.WriteLine ("You will have to check the results either by downloading with this client or with Tomboy original");
				}

			}

			Console.WriteLine ("Press return to finish");
					
			Console.ReadLine ();

		}

	}
}

